"""Add yearly_dates, start_time, end_time to MinistryActivities; refactor AttendanceInformation

Revision ID: 1ad2645d0d01
Revises: e1d0e06fd188
Create Date: 2026-02-08 23:19:19.675029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad2645d0d01'
down_revision: Union[str, None] = 'e1d0e06fd188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_training_category_id'), 'training_category', ['id'], unique=False)
    op.create_table('outreach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('assigned_pastor', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_pastor'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_id'), 'outreach', ['id'], unique=False)
    op.create_table('ministry_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_regular', sa.Boolean(), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('place', sa.String(length=255), nullable=True),
    sa.Column('outreach_id', sa.Integer(), nullable=True),
    sa.Column('schedule_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='scheduletype'), nullable=False),
    sa.Column('weekdays', sa.String(length=255), nullable=True),
    sa.Column('monthly_dates', sa.String(length=255), nullable=True),
    sa.Column('yearly_dates', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['outreach_id'], ['outreach.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ministry_activities_id'), 'ministry_activities', ['id'], unique=False)
    op.create_table('attendance_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=True),
    sa.Column('ministry_activity_id', sa.Integer(), nullable=False),
    sa.Column('ministry_type', sa.Enum('DISCIPLESHIP', 'TRAINING', 'CELEBRATION', 'EVANGELISM', name='ministrytype'), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ministry_activity_id'], ['ministry_activities.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_information_id'), 'attendance_information', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_information_user_id'), 'attendance_information', ['user_id'], unique=False)
    op.add_column('disciple_information', sa.Column('outreach_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'disciple_information', 'outreach', ['outreach_id'], ['id'])
    op.add_column('personal_information', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('personal_information', sa.Column('middle_name', sa.String(length=100), nullable=True))
    op.add_column('personal_information', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('personal_information', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('personal_information', sa.Column('profile_image', sa.String(length=255), nullable=True))
    op.drop_column('personal_information', 'age')
    op.add_column('trainings', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trainings', 'training_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainings', type_='foreignkey')
    op.drop_column('trainings', 'category_id')
    op.add_column('personal_information', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('personal_information', 'profile_image')
    op.drop_column('personal_information', 'birthday')
    op.drop_column('personal_information', 'last_name')
    op.drop_column('personal_information', 'middle_name')
    op.drop_column('personal_information', 'first_name')
    op.drop_constraint(None, 'disciple_information', type_='foreignkey')
    op.drop_column('disciple_information', 'outreach_id')
    op.drop_index(op.f('ix_attendance_information_user_id'), table_name='attendance_information')
    op.drop_index(op.f('ix_attendance_information_id'), table_name='attendance_information')
    op.drop_table('attendance_information')
    op.drop_index(op.f('ix_ministry_activities_id'), table_name='ministry_activities')
    op.drop_table('ministry_activities')
    op.drop_index(op.f('ix_outreach_id'), table_name='outreach')
    op.drop_table('outreach')
    op.drop_index(op.f('ix_training_category_id'), table_name='training_category')
    op.drop_table('training_category')
    # ### end Alembic commands ###
