"""Add new entities

Revision ID: e1d0e06fd188
Revises: 001_add_password
Create Date: 2026-01-31 17:40:41.622593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d0e06fd188'
down_revision: Union[str, None] = '001_add_password'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('scripture_reference', sa.String(length=100), nullable=True),
    sa.Column('devotion_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devotions_id'), 'devotions', ['id'], unique=False)
    op.create_index(op.f('ix_devotions_user_id'), 'devotions', ['user_id'], unique=False)
    op.create_table('disciple_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('PASTOR', 'VINE', 'CLUSTER', 'CARE_LEAD', 'DISCIPLE', name='disciplelevel'), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('joined_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciple_information_id'), 'disciple_information', ['id'], unique=False)
    op.create_index(op.f('ix_disciple_information_user_id'), 'disciple_information', ['user_id'], unique=True)
    op.create_table('personal_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_information_id'), 'personal_information', ['id'], unique=False)
    op.create_index(op.f('ix_personal_information_user_id'), 'personal_information', ['user_id'], unique=False)
    op.create_table('trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('trainer_name', sa.String(length=100), nullable=True),
    sa.Column('training_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completion_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainings_id'), 'trainings', ['id'], unique=False)
    op.create_index(op.f('ix_trainings_user_id'), 'trainings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainings_user_id'), table_name='trainings')
    op.drop_index(op.f('ix_trainings_id'), table_name='trainings')
    op.drop_table('trainings')
    op.drop_index(op.f('ix_personal_information_user_id'), table_name='personal_information')
    op.drop_index(op.f('ix_personal_information_id'), table_name='personal_information')
    op.drop_table('personal_information')
    op.drop_index(op.f('ix_disciple_information_user_id'), table_name='disciple_information')
    op.drop_index(op.f('ix_disciple_information_id'), table_name='disciple_information')
    op.drop_table('disciple_information')
    op.drop_index(op.f('ix_devotions_user_id'), table_name='devotions')
    op.drop_index(op.f('ix_devotions_id'), table_name='devotions')
    op.drop_table('devotions')
    # ### end Alembic commands ###
